server:
  port: 7000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_sales
    username: #username
    password: #password
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.example.CarSales.model.entity
security:
  secret-key: CgTOA2QC9nxYspeBZBRsEIoDmpBbGTjfDCE6WfnOHHrA7rgHafqC5u1m6GL22pNY
  expiration: 3000

#spring.datasource.url=jdbc:mysql://localhost:3306/car_sales
#spring.datasource.username=root
#spring.datasource.password=cehenemmeleyi01!
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#server.port=6000
#mybatis.config-location=classpath:mybatis/mybatis-config.xml
#mybatis.mapper-locations=classpath:mybatis/mapper/*.xml
#mybatis.type-aliases-package=com.example.CarSales.model.entity