server:
  port: 8010
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_sales
    username: root
    password: cehenemmeleyi01!
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
      properties:
       hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      database-platform: org.hibernate.dialect.MySQLDialect
mybatis:
   config-location: classpath:mybatis/mybatis-config.xml
   mapper-locations: classpath:mybatis/mapper/*.xml
   type-aliases-package: com.example.CarSales.model.entity
security:
  secret-key: CgTOA2QC9nxYspeBZBRsEIoDmpBbGTjfDCE6WfnOHHrA7rgHafqC5u1m6GL22pNz
  expiration: 3000

#spring.datasource.url=jdbc:mysql://localhost:3306/car_sales
#spring.datasource.username=root
#spring.datasource.password=cehenemmeleyi01!
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#server.port=6000
#mybatis.config-location=classpath:mybatis/mybatis-config.xml
#mybatis.mapper-locations=classpath:mybatis/mapper/*.xml
#mybatis.type-aliases-package=com.example.CarSales.model.entity